# Generated by Django 6.0.2 on 2026-03-12 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab2', '0001_initial'),
        ('users', '0002_usertoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='works', to='users.user'),
        ),
    ]
